### ISSUE TITLE
Cannot create new Tangos

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#27]
When trying to create a new Tango and filling all fields I can see (Sim name and description, Tango name, first statement), the following appears upon update:

`Failed to create Tango. All fields are required.`

Adding new statements or sims doesn't help.

**Comment by adamzerner** [comment]
Try deleting your account and creating a new one. Your current account was made before I made some changes to the code, and I think that that is causing the problem. If so, let me know and I'll close the issue.

**Comment by jrmyp** [comment]
Done, creating Tangos now works fine.
