### ISSUE TITLE
Unusable keyboard shortcuts

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#32]
The keyboard shortcuts are all of the form Ctrl + Cmd + [key]. However I don't have any Cmd key on my keyboard. I tried Ctrl + (Shift or Fn or Home or Alt or AltGr) + key, none of which work.

**Comment by adamzerner** [comment]
Fixed in [this](https://github.com/adamzerner/tango/commit/5fcaee87673eac3f21139cb44944e0d6806e9ca0) commit. I'm now showing what key to press for Windows users (when you hover over the icons).

See https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/metaKey
