### ISSUE TITLE
Unusable keyboard shortcuts (2)

### ISSUE THREAD

**Issue by jrmyp** [adamzerner/tango#40]
(I recreated a fresh account before trying)

The displayed keyboard shortcuts don't work, or partially. I'm running CentOS 6, and what works differs between browsers.

Chrome 46.0: All shortcuts work properly except
* Toogle Sim: conflicts with `Ctrl+J` shortcut which opens Downloads tab
* Indent Left-Right: no effect. I need `AltGr+5` or `AltGr+)` to reach brackets (AZERTY layout)

Firefox 38.3: No shortcut works. I couldn't add new statements as there are no toolbars anymore, so I tested after saving new statements with Chrome.

**Comment by adamzerner** [comment]
Sorry about this. Given that this hasn't gotten too big an audience, I don't think it's worth fixing. I appreciate you pointing it out though.
